# Generated by Django 3.0.5 on 2021-12-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField()),
                ('Pname', models.CharField(max_length=30)),
                ('Pstatus', models.CharField(choices=[('intiated', 'intiated'), ('started', 'started'), ('outForDelevary', 'outForDelevary'), ('deleverd', 'deleverd')], max_length=40)),
            ],
        ),
    ]
